version: '3'

services:

    database:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: exchangerates
            MYSQL_DATABASE: exchangerates
            MYSQL_USER: exchange_user
            MYSQL_PASSWORD: exchange_Pass

    redis:
        image: redis:5-alpine
        ports: [6379]
